// Generated by CoffeeScript 1.6.3
(function() {
  (function($) {
    return $.fn.setHeight = function(affectChildren) {
      var height;
      if (typeof affectChildren === "undefined" || affectChildren === null) {
        affectChildren = false;
      }
      height = [];
      this.each(function() {
        if (affectChildren) {
          height = [];
          $(this).children().each(function() {
            return height.push($(this).outerHeight());
          });
          return $(this).children().css("min-height", Math.max.apply(null, height));
        } else {
          return height.push($(this).outerHeight());
        }
      });
      if (!affectChildren) {
        return this.css("min-height", Math.max.apply(null, height));
      }
    };
  })(jQuery);

}).call(this);
